name: Python application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Run tests with coverage
      env:
        CONNECTION: "postgresql://postgres:postgres@localhost:5434/testdb"
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
        POSTGRES_DB: "testdb"
        PYTHONPATH: ${{ github.workspace }}
      run: |
        # Create a .env file for the tests
        echo "CONNECTION=postgresql://postgres:postgres@localhost:5434/testdb" > .env
        echo "POSTGRES_USER=postgres" >> .env
        echo "POSTGRES_PASSWORD=postgres" >> .env
        echo "POSTGRES_DB=testdb" >> .env
        
        # Run tests with a more reasonable coverage threshold
        pytest --cov=src --cov-report=xml --cov-fail-under=70

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.xml